version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sjt_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_job_tracker
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: sjt_server
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: smart_job_tracker
    ports:
      - "4000:4000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: sjt_client
    depends_on:
      - server
    ports:
      - "3000:80"
    restart: unless-stopped
