name: Build & Push Docker Images

on:
  push:
    branches: [master, main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase owner
        id: ow
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker info (debug)
        run: |
          docker info
          docker buildx version
          docker buildx ls

      # ------- Server -------
      - name: Build & Push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: true
          # GHCR requires lowercase owner/name
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sjt-server:latest
            ghcr.io/${{ env.OWNER_LC }}/sjt-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Work around first-push attestation hiccups
          provenance: false

      # ------- Client -------
      - name: Build & Push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL || 'http://localhost:4000' }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/sjt-client:latest
            ghcr.io/${{ env.OWNER_LC }}/sjt-client:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
