name: Build & Push Docker Images

on:
  push:
    branches: [master, main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sjt-server:latest

      - name: Build & push client (with VITE_API_URL)
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sjt-client:latest
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL || 'http://localhost:4000' }}
