name: Build & Push Docker Images

on:
  push:
    branches: [master, main]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ------- Server -------
      - name: Build & Push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/sjt-server:latest
            ghcr.io/${{ github.repository_owner }}/sjt-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ------- Client -------
      - name: Build & Push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL || 'http://localhost:4000' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/sjt-client:latest
            ghcr.io/${{ github.repository_owner }}/sjt-client:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
